

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
import java.sql.SQLException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iftiaj
 */
public class Donor extends javax.swing.JFrame {
    
    String user ="root";
    String pass ="112358.mysql";
    String url ="jdbc:mysql://localhost:3306/jdbc";
    int q, i, id, deleteItem;
    

    /**
     * Creates new form Donor
     */
   
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    //working with jtable 
    
    private int ID;
    private String Name;
    private String Blood_group;
    private String Med_report;
    private String Address;
    private int Contact;
    
    public Connection getConnection(){
       Connection con;

       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/jdbc", "root","112358.mysql");
           return con;
       } 
      catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
    
 

 
    
    public Donor(int id,String donor_name,String blood_group,String medical_report,String address,int contact)
    {
        this.ID = id;
        this.Name = donor_name;
        this.Blood_group = blood_group;
        this.Med_report = medical_report;
        this.Address = address;
        this.Contact = contact;
    }
    
    public int getId()
    {
        return ID;
    }
    
    public String getDonorName()
    {
        return Name;
    }
    
    public String getBloodGroup()
    {
        return Blood_group;
    }
     public String getMedReport()
    {
        return Med_report;
    }
      public String getAddress()
    {
        return Address;
    }
    
    public int getContact()
    {
        return Contact;
    }



   
    
    public Donor() {
        initComponents();
        
  
        this.setLocationRelativeTo(null); // centre window
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconMain.jpg")));
        this.setResizable(false);
        this.setTitle("Blood Donation Management System");
        this.getContentPane().setBackground(new Color(102,204,242,255)); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        bloodGroupLabel = new javax.swing.JLabel();
        medicalReportLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        bloodGroupText = new javax.swing.JTextField();
        contactText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        medicalReportText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        findText = new javax.swing.JTextField();
        findBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        updateBtn.setBackground(new java.awt.Color(0, 153, 153));
        updateBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 153, 51));
        saveBtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        saveBtn.setText("Add Donor");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(0, 153, 153));
        backBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nameLabel.setText("Name");

        bloodGroupLabel.setText("Blood group");

        medicalReportLabel.setText("Medical report");

        addressLabel.setText("Address");

        contactLabel.setText("Contact");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        findText.setText("Find by ID");
        findText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findTextMouseClicked(evt);
            }
        });
        findText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTextActionPerformed(evt);
            }
        });

        findBtn.setBackground(new java.awt.Color(0, 153, 153));
        findBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        findBtn.setText("Find");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloodGroupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicalReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medicalReportText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactText)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloodGroupText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressText))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(bloodGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloodGroupText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalReportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
//        updateData update = new updateData();
//        update = nameText.getText();
      
          //Update databsae
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              Connection con = DriverManager.getConnection(url, user, pass);
              
              String query = "UPDATE donor SET donor_name =?, blood_group = ?, medical_report =?, address=?,contact=? WHERE id =?";
              
              PreparedStatement ps = con.prepareStatement(query);
              ps.setString(1, nameText.getText());
              ps.setString(2, bloodGroupText.getText());
              ps.setString(3, medicalReportText.getText());
              ps.setString(4, addressText.getText());
              ps.setInt(5, Integer.parseInt(contactText.getText()));
              ps.setInt(6, Integer.parseInt(findText.getText()));
              
              ps.executeUpdate();
              JOptionPane.showMessageDialog(null, "Donor Information Updated");
              
              con.close();
              
            
               //setter to clear text field for re-entry data
               nameText.setText("");
               bloodGroupText.setText("");
               medicalReportText.setText("");
               addressText.setText("");
               contactText.setText("");
               
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
             
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        //Insert data into databsae    
      
         String donor_name, blood_group, medical_report, address, contact;

                //getter
                donor_name = nameText.getText();
                blood_group = bloodGroupText.getText();
                medical_report = medicalReportText.getText();
                address = addressText.getText();
                contact = contactText.getText();

                try{
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc", "root", "112358.mysql");
                    //Passing values into database
                    ps = con.prepareStatement("insert into donor(donor_name, blood_group, medical_report, address, contact) values(?,?,?,?,?)");

                    ps.setString(1, donor_name);
                    ps.setString(2, blood_group);
                    ps.setString(3, medical_report);
                    ps.setString(4, address);
                    ps.setString(5,contact);

                    //execute command
                    ps.executeUpdate();

                    //dialog to show confirmation
                    JOptionPane.showMessageDialog(null,"Donor Information Added");
                    //table1_load(); // not need in our program for now

                    //setter to clear text field for re-entry data
                    nameText.setText("");
                    bloodGroupText.setText("");
                    medicalReportText.setText("");
                    addressText.setText("");
                    contactText.setText("");

                }catch (SQLException e1){
                    e1.printStackTrace();
                }
         
    }//GEN-LAST:event_saveBtnActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Home homeFrame = new Home();
        homeFrame.show(); // display Donor frame
        
        dispose(); //close the current window
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_updateBtnMouseClicked

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:
            try{
            Connection con = DriverManager.getConnection(url, user, pass);
            
            String query = "SELECT * FROM donor WHERE id=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, findText.getText());
            
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                nameText.setText(rs.getString(("donor_name")));
                bloodGroupText.setText(rs.getString(("blood_group")));
                medicalReportText.setText(rs.getString(("medical_report")));
                addressText.setText(rs.getString(("address")));
                contactText.setText(rs.getString(("contact")));
                
            }else{
                JOptionPane.showMessageDialog(null, "Donor not found. Try a valid ID");
            }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_findBtnActionPerformed

    private void findTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findTextMouseClicked
        // TODO add your handling code here:
         findText.setText("");
        
    }//GEN-LAST:event_findTextMouseClicked

    private void findTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    public javax.swing.JTextField addressText;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bloodGroupLabel;
    public javax.swing.JTextField bloodGroupText;
    private javax.swing.JLabel contactLabel;
    public javax.swing.JTextField contactText;
    private javax.swing.JButton findBtn;
    private javax.swing.JTextField findText;
    private javax.swing.JLabel medicalReportLabel;
    public javax.swing.JTextField medicalReportText;
    private javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameText;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void updateDB() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
